[pytest]

# cache dir
cache_dir = temp/.pytest_cache

# addopts
addopts = -s -v

# test files
python_files = test_*.py *_test.py

# test classes
python_classes = Test*

# test functions
python_functions = test_*

